import { OptionType } from 'interfaces';

export const country: OptionType[] = [
	{
		text: 'Select...',
		value: '',
		disabled: false,
		placeholder: true,
	},
	{ text: 'Afghanistan', value: 'AF', disabled: false, placeholder: false },
	{ text: 'Åland Islands', value: 'AX', disabled: false, placeholder: false },
	{ text: 'Albania', value: 'AL', disabled: false, placeholder: false },
	{ text: 'Algeria', value: 'DZ', disabled: false, placeholder: false },
	{ text: 'American Samoa', value: 'AS', disabled: false, placeholder: false },
	{ text: 'AndorrA', value: 'AD', disabled: false, placeholder: false },
	{ text: 'Angola', value: 'AO', disabled: false, placeholder: false },
	{ text: 'Anguilla', value: 'AI', disabled: false, placeholder: false },
	{ text: 'Antarctica', value: 'AQ', disabled: false, placeholder: false },
	{
		text: 'Antigua and Barbuda',
		value: 'AG',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Argentina', value: 'AR', disabled: false, placeholder: false },
	{ text: 'Armenia', value: 'AM', disabled: false, placeholder: false },
	{ text: 'Aruba', value: 'AW', disabled: false, placeholder: false },
	{ text: 'Australia', value: 'AU', disabled: false, placeholder: false },
	{ text: 'Austria', value: 'AT', disabled: false, placeholder: false },
	{ text: 'Azerbaijan', value: 'AZ', disabled: false, placeholder: false },
	{ text: 'Bahamas', value: 'BS', disabled: false, placeholder: false },
	{ text: 'Bahrain', value: 'BH', disabled: false, placeholder: false },
	{ text: 'Bangladesh', value: 'BD', disabled: false, placeholder: false },
	{ text: 'Barbados', value: 'BB', disabled: false, placeholder: false },
	{ text: 'Belarus', value: 'BY', disabled: false, placeholder: false },
	{ text: 'Belgium', value: 'BE', disabled: false, placeholder: false },
	{ text: 'Belize', value: 'BZ', disabled: false, placeholder: false },
	{ text: 'Benin', value: 'BJ', disabled: false, placeholder: false },
	{ text: 'Bermuda', value: 'BM', disabled: false, placeholder: false },
	{ text: 'Bhutan', value: 'BT', disabled: false, placeholder: false },
	{ text: 'Bolivia', value: 'BO', disabled: false, placeholder: false },
	{
		text: 'Bosnia and Herzegovina',
		value: 'BA',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Botswana', value: 'BW', disabled: false, placeholder: false },
	{ text: 'Bouvet Island', value: 'BV', disabled: false, placeholder: false },
	{ text: 'Brazil', value: 'BR', disabled: false, placeholder: false },
	{
		text: 'British Indian Ocean Territory',
		value: 'IO',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Brunei Darussalam',
		value: 'BN',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Bulgaria', value: 'BG', disabled: false, placeholder: false },
	{ text: 'Burkina Faso', value: 'BF', disabled: false, placeholder: false },
	{ text: 'Burundi', value: 'BI', disabled: false, placeholder: false },
	{ text: 'Cambodia', value: 'KH', disabled: false, placeholder: false },
	{ text: 'Cameroon', value: 'CM', disabled: false, placeholder: false },
	{ text: 'Canada', value: 'CA', disabled: false, placeholder: false },
	{ text: 'Cape Verde', value: 'CV', disabled: false, placeholder: false },
	{ text: 'Cayman Islands', value: 'KY', disabled: false, placeholder: false },
	{
		text: 'Central African Republic',
		value: 'CF',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Chad', value: 'TD', disabled: false, placeholder: false },
	{ text: 'Chile', value: 'CL', disabled: false, placeholder: false },
	{ text: 'China', value: 'CN', disabled: false, placeholder: false },
	{
		text: 'Christmas Island',
		value: 'CX',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Cocos (Keeling) Islands',
		value: 'CC',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Colombia', value: 'CO', disabled: false, placeholder: false },
	{ text: 'Comoros', value: 'KM', disabled: false, placeholder: false },
	{ text: 'Congo', value: 'CG', disabled: false, placeholder: false },
	{
		text: 'Congo, The Democratic Republic of the',
		value: 'CD',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Cook Islands', value: 'CK', disabled: false, placeholder: false },
	{ text: 'Costa Rica', value: 'CR', disabled: false, placeholder: false },
	{ text: "Cote D'Ivoire", value: 'CI', disabled: false, placeholder: false },
	{ text: 'Croatia', value: 'HR', disabled: false, placeholder: false },
	{ text: 'Cuba', value: 'CU', disabled: false, placeholder: false },
	{ text: 'Cyprus', value: 'CY', disabled: false, placeholder: false },
	{ text: 'Czech Republic', value: 'CZ', disabled: false, placeholder: false },
	{ text: 'Denmark', value: 'DK', disabled: false, placeholder: false },
	{ text: 'Djibouti', value: 'DJ', disabled: false, placeholder: false },
	{ text: 'Dominica', value: 'DM', disabled: false, placeholder: false },
	{
		text: 'Dominican Republic',
		value: 'DO',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Ecuador', value: 'EC', disabled: false, placeholder: false },
	{ text: 'Egypt', value: 'EG', disabled: false, placeholder: false },
	{ text: 'El Salvador', value: 'SV', disabled: false, placeholder: false },
	{
		text: 'Equatorial Guinea',
		value: 'GQ',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Eritrea', value: 'ER', disabled: false, placeholder: false },
	{ text: 'Estonia', value: 'EE', disabled: false, placeholder: false },
	{ text: 'Ethiopia', value: 'ET', disabled: false, placeholder: false },
	{
		text: 'Falkland Islands (Malvinas)',
		value: 'FK',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Faroe Islands', value: 'FO', disabled: false, placeholder: false },
	{ text: 'Fiji', value: 'FJ', disabled: false, placeholder: false },
	{ text: 'Finland', value: 'FI', disabled: false, placeholder: false },
	{ text: 'France', value: 'FR', disabled: false, placeholder: false },
	{ text: 'French Guiana', value: 'GF', disabled: false, placeholder: false },
	{
		text: 'French Polynesia',
		value: 'PF',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'French Southern Territories',
		value: 'TF',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Gabon', value: 'GA', disabled: false, placeholder: false },
	{ text: 'Gambia', value: 'GM', disabled: false, placeholder: false },
	{ text: 'Georgia', value: 'GE', disabled: false, placeholder: false },
	{ text: 'Germany', value: 'DE', disabled: false, placeholder: false },
	{ text: 'Ghana', value: 'GH', disabled: false, placeholder: false },
	{ text: 'Gibraltar', value: 'GI', disabled: false, placeholder: false },
	{ text: 'Greece', value: 'GR', disabled: false, placeholder: false },
	{ text: 'Greenland', value: 'GL', disabled: false, placeholder: false },
	{ text: 'Grenada', value: 'GD', disabled: false, placeholder: false },
	{ text: 'Guadeloupe', value: 'GP', disabled: false, placeholder: false },
	{ text: 'Guam', value: 'GU', disabled: false, placeholder: false },
	{ text: 'Guatemala', value: 'GT', disabled: false, placeholder: false },
	{ text: 'Guernsey', value: 'GG', disabled: false, placeholder: false },
	{ text: 'Guinea', value: 'GN', disabled: false, placeholder: false },
	{ text: 'Guinea-Bissau', value: 'GW', disabled: false, placeholder: false },
	{ text: 'Guyana', value: 'GY', disabled: false, placeholder: false },
	{ text: 'Haiti', value: 'HT', disabled: false, placeholder: false },
	{
		text: 'Heard Island and Mcdonald Islands',
		value: 'HM',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Holy See (Vatican City State)',
		value: 'VA',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Honduras', value: 'HN', disabled: false, placeholder: false },
	{ text: 'Hong Kong', value: 'HK', disabled: false, placeholder: false },
	{ text: 'Hungary', value: 'HU', disabled: false, placeholder: false },
	{ text: 'Iceland', value: 'IS', disabled: false, placeholder: false },
	{ text: 'India', value: 'IN', disabled: false, placeholder: false },
	{ text: 'Indonesia', value: 'ID', disabled: false, placeholder: false },
	{
		text: 'Iran, Islamic Republic Of',
		value: 'IR',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Iraq', value: 'IQ', disabled: false, placeholder: false },
	{ text: 'Ireland', value: 'IE', disabled: false, placeholder: false },
	{ text: 'Isle of Man', value: 'IM', disabled: false, placeholder: false },
	{ text: 'Israel', value: 'IL', disabled: false, placeholder: false },
	{ text: 'Italy', value: 'IT', disabled: false, placeholder: false },
	{ text: 'Jamaica', value: 'JM', disabled: false, placeholder: false },
	{ text: 'Japan', value: 'JP', disabled: false, placeholder: false },
	{ text: 'Jersey', value: 'JE', disabled: false, placeholder: false },
	{ text: 'Jordan', value: 'JO', disabled: false, placeholder: false },
	{ text: 'Kazakhstan', value: 'KZ', disabled: false, placeholder: false },
	{ text: 'Kenya', value: 'KE', disabled: false, placeholder: false },
	{ text: 'Kiribati', value: 'KI', disabled: false, placeholder: false },
	{
		text: "Korea, Democratic People'S Republic of",
		value: 'KP',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Korea, Republic of',
		value: 'KR',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Kuwait', value: 'KW', disabled: false, placeholder: false },
	{ text: 'Kyrgyzstan', value: 'KG', disabled: false, placeholder: false },
	{
		text: "Lao People'S Democratic Republic",
		value: 'LA',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Latvia', value: 'LV', disabled: false, placeholder: false },
	{ text: 'Lebanon', value: 'LB', disabled: false, placeholder: false },
	{ text: 'Lesotho', value: 'LS', disabled: false, placeholder: false },
	{ text: 'Liberia', value: 'LR', disabled: false, placeholder: false },
	{
		text: 'Libyan Arab Jamahiriya',
		value: 'LY',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Liechtenstein', value: 'LI', disabled: false, placeholder: false },
	{ text: 'Lithuania', value: 'LT', disabled: false, placeholder: false },
	{ text: 'Luxembourg', value: 'LU', disabled: false, placeholder: false },
	{ text: 'Macao', value: 'MO', disabled: false, placeholder: false },
	{
		text: 'Macedonia, The Former Yugoslav Republic of',
		value: 'MK',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Madagascar', value: 'MG', disabled: false, placeholder: false },
	{ text: 'Malawi', value: 'MW', disabled: false, placeholder: false },
	{ text: 'Malaysia', value: 'MY', disabled: false, placeholder: false },
	{ text: 'Maldives', value: 'MV', disabled: false, placeholder: false },
	{ text: 'Mali', value: 'ML', disabled: false, placeholder: false },
	{ text: 'Malta', value: 'MT', disabled: false, placeholder: false },
	{
		text: 'Marshall Islands',
		value: 'MH',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Martinique', value: 'MQ', disabled: false, placeholder: false },
	{ text: 'Mauritania', value: 'MR', disabled: false, placeholder: false },
	{ text: 'Mauritius', value: 'MU', disabled: false, placeholder: false },
	{ text: 'Mayotte', value: 'YT', disabled: false, placeholder: false },
	{ text: 'Mexico', value: 'MX', disabled: false, placeholder: false },
	{
		text: 'Micronesia, Federated States of',
		value: 'FM',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Moldova, Republic of',
		value: 'MD',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Monaco', value: 'MC', disabled: false, placeholder: false },
	{ text: 'Mongolia', value: 'MN', disabled: false, placeholder: false },
	{ text: 'Montserrat', value: 'MS', disabled: false, placeholder: false },
	{ text: 'Morocco', value: 'MA', disabled: false, placeholder: false },
	{ text: 'Mozambique', value: 'MZ', disabled: false, placeholder: false },
	{ text: 'Myanmar', value: 'MM', disabled: false, placeholder: false },
	{ text: 'Namibia', value: 'NA', disabled: false, placeholder: false },
	{ text: 'Nauru', value: 'NR', disabled: false, placeholder: false },
	{ text: 'Nepal', value: 'NP', disabled: false, placeholder: false },
	{ text: 'Netherlands', value: 'NL', disabled: false, placeholder: false },
	{
		text: 'Netherlands Antilles',
		value: 'AN',
		disabled: false,
		placeholder: false,
	},
	{ text: 'New Caledonia', value: 'NC', disabled: false, placeholder: false },
	{ text: 'New Zealand', value: 'NZ', disabled: false, placeholder: false },
	{ text: 'Nicaragua', value: 'NI', disabled: false, placeholder: false },
	{ text: 'Niger', value: 'NE', disabled: false, placeholder: false },
	{ text: 'Nigeria', value: 'NG', disabled: false, placeholder: false },
	{ text: 'Niue', value: 'NU', disabled: false, placeholder: false },
	{ text: 'Norfolk Island', value: 'NF', disabled: false, placeholder: false },
	{
		text: 'Northern Mariana Islands',
		value: 'MP',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Norway', value: 'NO', disabled: false, placeholder: false },
	{ text: 'Oman', value: 'OM', disabled: false, placeholder: false },
	{ text: 'Pakistan', value: 'PK', disabled: false, placeholder: false },
	{ text: 'Palau', value: 'PW', disabled: false, placeholder: false },
	{
		text: 'Palestinian Territory, Occupied',
		value: 'PS',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Panama', value: 'PA', disabled: false, placeholder: false },
	{
		text: 'Papua New Guinea',
		value: 'PG',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Paraguay', value: 'PY', disabled: false, placeholder: false },
	{ text: 'Peru', value: 'PE', disabled: false, placeholder: false },
	{ text: 'Philippines', value: 'PH', disabled: false, placeholder: false },
	{ text: 'Pitcairn', value: 'PN', disabled: false, placeholder: false },
	{ text: 'Poland', value: 'PL', disabled: false, placeholder: false },
	{ text: 'Portugal', value: 'PT', disabled: false, placeholder: false },
	{ text: 'Puerto Rico', value: 'PR', disabled: false, placeholder: false },
	{ text: 'Qatar', value: 'QA', disabled: false, placeholder: false },
	{ text: 'Reunion', value: 'RE', disabled: false, placeholder: false },
	{ text: 'Romania', value: 'RO', disabled: false, placeholder: false },
	{
		text: 'Russian Federation',
		value: 'RU',
		disabled: false,
		placeholder: false,
	},
	{ text: 'RWANDA', value: 'RW', disabled: false, placeholder: false },
	{ text: 'Saint Helena', value: 'SH', disabled: false, placeholder: false },
	{
		text: 'Saint Kitts and Nevis',
		value: 'KN',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Saint Lucia', value: 'LC', disabled: false, placeholder: false },
	{
		text: 'Saint Pierre and Miquelon',
		value: 'PM',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Saint Vincent and the Grenadines',
		value: 'VC',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Samoa', value: 'WS', disabled: false, placeholder: false },
	{ text: 'San Marino', value: 'SM', disabled: false, placeholder: false },
	{
		text: 'Sao Tome and Principe',
		value: 'ST',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Saudi Arabia', value: 'SA', disabled: false, placeholder: false },
	{ text: 'Senegal', value: 'SN', disabled: false, placeholder: false },
	{
		text: 'Serbia and Montenegro',
		value: 'CS',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Seychelles', value: 'SC', disabled: false, placeholder: false },
	{ text: 'Sierra Leone', value: 'SL', disabled: false, placeholder: false },
	{ text: 'Singapore', value: 'SG', disabled: false, placeholder: false },
	{ text: 'Slovakia', value: 'SK', disabled: false, placeholder: false },
	{ text: 'Slovenia', value: 'SI', disabled: false, placeholder: false },
	{ text: 'Solomon Islands', value: 'SB', disabled: false, placeholder: false },
	{ text: 'Somalia', value: 'SO', disabled: false, placeholder: false },
	{ text: 'South Africa', value: 'ZA', disabled: false, placeholder: false },
	{
		text: 'South Georgia and the South Sandwich Islands',
		value: 'GS',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Spain', value: 'ES', disabled: false, placeholder: false },
	{ text: 'Sri Lanka', value: 'LK', disabled: false, placeholder: false },
	{ text: 'Sudan', value: 'SD', disabled: false, placeholder: false },
	{ text: 'Suritext', value: 'SR', disabled: false, placeholder: false },
	{
		text: 'Svalbard and Jan Mayen',
		value: 'SJ',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Swaziland', value: 'SZ', disabled: false, placeholder: false },
	{ text: 'Sweden', value: 'SE', disabled: false, placeholder: false },
	{ text: 'Switzerland', value: 'CH', disabled: false, placeholder: false },
	{
		text: 'Syrian Arab Republic',
		value: 'SY',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Taiwan, Province of China',
		value: 'TW',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Tajikistan', value: 'TJ', disabled: false, placeholder: false },
	{
		text: 'Tanzania, United Republic of',
		value: 'TZ',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Thailand', value: 'TH', disabled: false, placeholder: false },
	{ text: 'Timor-Leste', value: 'TL', disabled: false, placeholder: false },
	{ text: 'Togo', value: 'TG', disabled: false, placeholder: false },
	{ text: 'Tokelau', value: 'TK', disabled: false, placeholder: false },
	{ text: 'Tonga', value: 'TO', disabled: false, placeholder: false },
	{
		text: 'Trinidad and Tobago',
		value: 'TT',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Tunisia', value: 'TN', disabled: false, placeholder: false },
	{ text: 'Turkey', value: 'TR', disabled: false, placeholder: false },
	{ text: 'Turkmenistan', value: 'TM', disabled: false, placeholder: false },
	{
		text: 'Turks and Caicos Islands',
		value: 'TC',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Tuvalu', value: 'TV', disabled: false, placeholder: false },
	{ text: 'Uganda', value: 'UG', disabled: false, placeholder: false },
	{ text: 'Ukraine', value: 'UA', disabled: false, placeholder: false },
	{
		text: 'United Arab Emirates',
		value: 'AE',
		disabled: false,
		placeholder: false,
	},
	{ text: 'United Kingdom', value: 'GB', disabled: false, placeholder: false },
	{ text: 'United States', value: 'US', disabled: false, placeholder: false },
	{
		text: 'United States Minor Outlying Islands',
		value: 'UM',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Uruguay', value: 'UY', disabled: false, placeholder: false },
	{ text: 'Uzbekistan', value: 'UZ', disabled: false, placeholder: false },
	{ text: 'Vanuatu', value: 'VU', disabled: false, placeholder: false },
	{ text: 'Venezuela', value: 'VE', disabled: false, placeholder: false },
	{ text: 'Viet Nam', value: 'VN', disabled: false, placeholder: false },
	{
		text: 'Virgin Islands, British',
		value: 'VG',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Virgin Islands, U.S.',
		value: 'VI',
		disabled: false,
		placeholder: false,
	},
	{
		text: 'Wallis and Futuna',
		value: 'WF',
		disabled: false,
		placeholder: false,
	},
	{ text: 'Western Sahara', value: 'EH', disabled: false, placeholder: false },
	{ text: 'Yemen', value: 'YE', disabled: false, placeholder: false },
	{ text: 'Zambia', value: 'ZM', disabled: false, placeholder: false },
	{ text: 'Zimbabwe', value: 'ZW', disabled: false, placeholder: false },
];
